export const LOGIN = 'LOGIN';
export const GET_CART_ITEMS_STARTED = 'GET_CART_ITEMS_STARTED';
export const GET_CART_ITEMS_SUCCESS = 'GET_CART_ITEMS_SUCCESS';
export const GET_CART_ITEMS_FAIL = 'GET_CART_ITEMS_FAIL';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const LOAD_PRODUCTS_STARTED = 'LOAD_PRODUCTS_STARTED';
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCTS_FAIL = 'LOAD_PRODUCTS_FAIL';
export const LOAD_PRODUCT_STARTED = 'LOAD_PRODUCT_STARTED'
export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS';
export const LOAD_PRODUCT_FAIL = 'LOAD_PRODUCT_FAIL';




